package config;

public enum StateRepresentation {
    SALIENCE_4X4_BINARY,
    SALIENCE_4X4_CONTINUOUS,
    SALIENCE_8X8_CONTINUOUS,
    SALIENCE_16X16_CONTINUOUS,
    SALIENCE_16X16_WITH_INTERNAL_STATE
}